:encoding: utf-8
:lang: ja

= くぼあきの自己紹介

== わたしのこと

[options="header"]
|===
| 氏名 | 学籍番号 | メールアドレス

| 久保秋　真（くぼあき　しん）
| 学籍番号はありません…
| kuboaki.shin@nihon-u.ac.jp
|===

== 最近読んだ本の紹介

=== ザ・チョイス―複雑さに惑わされるな!

==== 紹介文

複雑なソリューションなんて、うまくいくわけがない!
（...略...）
本当に重要なポイント、数少ないわずかなポイントを探し出し、それだけに努力を集中することでシステム全体に変化を起こすことができると主張する。
その方法を学ぶことで、システムの中に存在する複雑な因果関係ffに対しても、シンプルなロジックを用いて最小限の努力で対応できるようになる。

==== 感想・コメント

「ザ・ゴール」から始まるゴールドラット一連のシリーズの5冊目。 +
制約理論や思考プロセスといった彼の考え方の背景にあるものはなにか、彼がなぜそのような思考でソリューションを導くことができるのかといったことに踏み込んでいる。
（...略...）実は、われわれは先入観に支配されがちで、誰もが簡単に実行できることでも、気づかなかったり、実行は難しいと考えてしまったりしているのだ。
この本は後者の克服にこそ飛躍的な問題可決方法が隠れているが、それを見出すのは容易ではないことを教えてくれている。

==== アマゾンで調べる

http://www.amazon.co.jp/dp/4478006652/[「ザ・チョイス―複雑さに惑わされるな!」]

== 最近買ったものの紹介

=== 「ナルニア国物語/第2章:カスピアン王子の角笛」のDVD

==== 紹介文

『ナルニア国物語/第1章:ライオンと魔女』に続く物語。 +
ナルニア暦2303年。ミラーズに支配されてしまったナルニア。
追い詰められたカスピアン王子は、コルネリウス博士から託された角笛を吹き鳴らし、偉大なる4人の王を甦らせる。
ナルニアの未来を懸けた決戦が、いま始まる。

==== 紹介しているサイト

http://www.amazon.co.jp/ナルニア国物語-第2章-カスピアン王子の角笛-DVD/dp/B002SCP792[「ナルニア国物語/第2章:カスピアン王子の角笛」（DVD）]

